# Generated by Django 4.2.9 on 2024-03-06 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentModel',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_email', models.EmailField(max_length=255)),
                ('agent_password', models.CharField(max_length=255)),
                ('agent_phone', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('license', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'agent_data',
            },
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hotel_data',
            },
        ),
        migrations.CreateModel(
            name='NationsModel',
            fields=[
                ('nations_id', models.AutoField(primary_key=True, serialize=False)),
                ('nation', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nations',
            },
        ),
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('activities', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgentApp.agentmodel')),
                ('nation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgentApp.nationsmodel')),
            ],
            options={
                'db_table': 'PackageModel',
            },
        ),
        migrations.CreateModel(
            name='PackageSplit',
            fields=[
                ('package_split_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgentApp.packagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PackageImagesModel',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgentApp.packagemodel')),
            ],
            options={
                'db_table': 'package_images',
            },
        ),
        migrations.CreateModel(
            name='PackageHotel',
            fields=[
                ('package_hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgentApp.hotelmodel')),
                ('package_split_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgentApp.packagesplit')),
            ],
            options={
                'db_table': 'package_hotel',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('hotel_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_image', models.ImageField(upload_to='images')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgentApp.hotelmodel')),
            ],
            options={
                'db_table': 'hotel_image',
            },
        ),
        migrations.CreateModel(
            name='ActivitiesModel',
            fields=[
                ('activities_id', models.AutoField(primary_key=True, serialize=False)),
                ('activities', models.CharField(max_length=255)),
                ('activity_description', models.CharField(max_length=255)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgentApp.packagemodel')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
