# Generated by Django 4.2.9 on 2024-03-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packagesplit',
            table='package_split',
        ),
    ]
