# Generated by Django 4.2.9 on 2024-03-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0003_remove_packagemodel_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesmodel',
            name='activities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitiesmodel',
            name='activity_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitiesmodel',
            name='activity_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
