# Generated by Django 4.2.9 on 2024-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0004_alter_activitiesmodel_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesmodel',
            name='activities',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitiesmodel',
            name='activity_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitiesmodel',
            name='activity_images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
