# Generated by Django 4.2.9 on 2024-04-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0005_alter_activitiesmodel_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
