# Generated by Django 4.2.9 on 2024-04-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0006_alter_packagemodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('status', models.CharField(default='active', max_length=255)),
                ('applicable_agents', models.ManyToManyField(to='AgentApp.agentmodel')),
                ('applicable_packages', models.ManyToManyField(to='AgentApp.packagemodel')),
            ],
            options={
                'db_table': 'offers',
            },
        ),
    ]
