# Generated by Django 4.2.9 on 2024-04-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0008_remove_offermodel_applicable_packages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemodel',
            name='offer',
        ),
        migrations.AddField(
            model_name='offermodel',
            name='applicable_packages',
            field=models.ManyToManyField(to='AgentApp.packagemodel'),
        ),
    ]
