# Generated by Django 4.2.9 on 2024-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0009_remove_packagemodel_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='applicable_packages',
            field=models.ManyToManyField(related_name='offers', to='AgentApp.packagemodel'),
        ),
    ]
