# Generated by Django 4.2.9 on 2024-04-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0010_alter_offermodel_applicable_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimagesmodel',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AgentApp.packagemodel'),
        ),
    ]
