# Generated by Django 4.2.9 on 2024-04-11 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0012_packagemodel_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagehotel',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_hotels', to='AgentApp.hotelmodel'),
        ),
    ]
