# Generated by Django 4.2.9 on 2024-04-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0013_alter_packagehotel_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagehotel',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgentApp.hotelmodel'),
        ),
    ]
