# Generated by Django 4.2.9 on 2024-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0014_alter_packagehotel_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmodel',
            name='hotel_description',
            field=models.TextField(null=True),
        ),
    ]
