# Generated by Django 4.2.8 on 2024-04-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0015_hotelmodel_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='status',
            field=models.CharField(default='inactive', max_length=255),
        ),
    ]
