# Generated by Django 4.2.9 on 2024-04-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminmodel',
            name='reg_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminmodel',
            name='status',
            field=models.CharField(default='inactive', max_length=255),
        ),
    ]
