# Generated by Django 4.2.9 on 2024-02-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOOKING_SER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('depart', models.DateField(max_length=255)),
                ('return1', models.DateField(max_length=255)),
                ('adult', models.IntegerField(max_length=255)),
                ('children', models.IntegerField(max_length=255)),
            ],
            options={
                'db_table': 'booking_ser',
            },
        ),
    ]
