# Generated by Django 4.2.9 on 2024-02-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_ser',
            name='adult',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking_ser',
            name='children',
            field=models.IntegerField(),
        ),
    ]
