# Generated by Django 4.2.9 on 2024-03-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_bookingmodel_paymenttype_usermodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BOOKING_SER',
        ),
    ]
