# Generated by Django 4.2.9 on 2024-04-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0012_packagemodel_is_recommended'),
        ('UserApp', '0005_websitereviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='package_id',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='AgentApp.packagemodel'),
        ),
    ]
