# Generated by Django 4.2.9 on 2024-04-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0012_packagemodel_is_recommended'),
        ('UserApp', '0006_remove_feedbackmodel_package_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='package',
        ),
        migrations.CreateModel(
            name='WishlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AgentApp.packagemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel')),
            ],
            options={
                'unique_together': {('user', 'package')},
            },
        ),
    ]
