# Generated by Django 4.2.9 on 2024-04-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0012_packagemodel_is_recommended'),
        ('UserApp', '0007_remove_feedbackmodel_package_wishlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='package_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AgentApp.packagemodel'),
        ),
    ]
