# Generated by Django 4.2.9 on 2024-04-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_feedbackmodel_package_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistmodel',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='wishlistmodel',
            table='wishlist',
        ),
    ]
