# Generated by Django 4.2.9 on 2024-04-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0012_packagemodel_is_recommended'),
        ('UserApp', '0009_alter_wishlistmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistmodel',
            unique_together={('user', 'package')},
        ),
        migrations.AlterModelTable(
            name='wishlistmodel',
            table=None,
        ),
    ]
