# Generated by Django 4.2.9 on 2024-04-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_alter_feedbackmodel_package_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='special_request',
        ),
    ]
