# Generated by Django 4.2.9 on 2024-04-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_remove_bookingmodel_special_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='car_rental',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
