# Generated by Django 4.2.9 on 2024-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_bookingmodel_car_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='payment_status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
