# Generated by Django 4.2.9 on 2024-04-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_alter_bookingmodel_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='status',
        ),
    ]
