# Generated by Django 4.2.9 on 2024-04-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_bookingmodel_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='booking_status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
