# Generated by Django 4.2.11 on 2024-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0019_usermodel_gender_usermodel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(default='-not added-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='location',
            field=models.CharField(default='-not added-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_dob',
            field=models.CharField(default='-not added-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_mobile',
            field=models.CharField(default='-not added-', max_length=255, null=True),
        ),
    ]
